version: '3.8'

services:
  employee-service:
    container_name: employee-service
    build:
      context: ./employee-service
    ports:
      - "8082:8082"
    networks:
      - employee-network
    environment:
      - SERVER_PORT=8082
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-client:
    container_name: employee-client
    build:
      context: ./employee-client
    ports:
      - "8081:8081"
    depends_on:
      employee-service:
        condition: service_healthy
    networks:
      - employee-network
    environment:
      - SERVER_PORT=8081
      - EMPLOYEE_SERVICE_URL=http://employee-service:8082  # 👈 important: Docker DNS name

networks:
  employee-network:
    driver: bridge
